### PR TITLE
fish

### PR DESCRIPTION
**Pull request by lollilol**
fish

### CODE REVIEW

**Comment by lollilol** [comment]
merge when

**Comment by homamgamer** [comment]
this must be merged

**Comment by lollilol** [comment]
when are you gonna merge it

**Comment by XandarNull** [comment]
yes true, merge when

**Comment by lollilol** [comment]
im waiting for your answer sir.

**Comment by XandarNull** [comment]
same

**Comment by lollilol** [comment]
why does the dev not respond to this important pr?

**Comment by Ibrahimxelil** [comment]
Hi guys, How can I get this bot to work?

**Comment by lollilol** [comment]
python3 -m ubot

**Comment by Ibrahimxelil** [comment]
It would be nice to share link for automatically deploy(heroku). (Telegram)

**Comment by lollilol** [comment]
stfu peasant

**Comment by lollilol** [comment]
still waiting for the merge

**Comment by XandarNull** [comment]
merge now or else

**Comment by XandarNull** [comment]
merge when?

**Comment by XandarNull** [comment]
still waiting btw

**Comment by lollilol** [comment]
When are you gonna merge?

**Comment by XandarNull** [comment]
WHAT, noooooo

**Comment by lollilol** [comment]
unacceptable

**Pull request closed without merging**
